apiVersion: v1
kind: Service
metadata:
  name: php-service
spec:
  selector:
    app: php # Le sélecteur doit correspondre au libellé du déploiement
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 80
    nodePort: 30030
  type: NodePort

  