apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment-terra
  namespace: mysql-dep-terra
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql-container
        image: sopd/mysql_img
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: your-root-password
