apiVersion: v1
kind: Service
metadata:
  name: php-service-terra
  namespace: php-serv-terra
spec:
  selector:
    app: php
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
