apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-deployment-terra
  namespace: php-dep-terra
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php
  template:
    metadata:
      labels:
        app: php
    spec:
      containers:
      - name: php-container
        image: sopd / mon_php_img
        ports:
        - containerPort: 80
